version: 2.1

orbs:
  node: circleci/node@5.1
  azure-cli: circleci/azure-cli@1.2
  terraform: circleci/terraform@3.2

jobs:
  plan:
    docker:
      - image: cimg/node:21.3
    steps:
      - checkout
      - run: 
          name: Install dependencies and Plan
          command: |
            cd infra
            yarn install
            npx cdktf get
            npx cdktf plan

  apply:
    docker:
      - image: cimg/node:21.3
    steps:
      - checkout
      - run: 
          name: Install dependencies and Apply
          command: |
            cd infra
            yarn install
            npx cdktf apply --auto-approve

workflows:
  build_and_deploy:
    jobs:
      - plan
      - approve:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - approve
