version: 2.1

orbs:
  node: circleci/node@5.1
  azure-cli: circleci/azure-cli@1.2
  terraform: circleci/terraform@3.2

jobs:
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            cd infra
            yarn set version 4.0.2
            yarn --version 
            yarn install
            yarn get
      - save_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
          paths:
            - infra/yarn.lock
            - infra/node_modules

  synth:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
      - run: 
          name: Install dependencies and Synth
          command: |
            cd infra
            yarn --version
            yarn install
            yarn get
            yarn synth
  plan:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
      - run:
          name: Install terraform cli
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - run: 
          name: Install dependencies and Plan
          command: |
            cd infra
            yarn install
            yarn --version 
            yarn get
            yarn plan

  apply:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
      - run: 
          name: Install dependencies and Apply
          command: |
            cd infra
            yarn --version
            yarn install
            yarn get
            yarn apply:auto-approve

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - synth:
          filters:
            branches:
              only:
                - main
          requires:
            - install_dependencies
      - plan:
          filters:
            branches:
              only:
                - main
          requires:
              - synth
      - approve:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - plan
      - apply:
          filters:
            branches:
              only:
                - main
          requires:
            - approve
