version: 2.1

orbs:
  node: circleci/node@5.1
  azure-cli: circleci/azure-cli@1.2
  terraform: circleci/terraform@3.2

jobs:
  install_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            cd infra
            yarn set version 4.0.2
            yarn --version 
            yarn install
            yarn get
      - save_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
          paths:
            - infra/yarn.lock
            - infra/node_modules
  plan:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
      - run: 
          name: Install dependencies and Plan
          command: |
            cd infra
            yarn install
            yarn --version 
            yarn get
            yarn plan

  apply:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "infra/yarn.lock" }}
      - run: 
          name: Install dependencies and Apply
          command: |
            cd infra
            yarn --version
            yarn install
            yarn get
            yarn apply:auto-approve

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - plan:
          requires:
              - install_dependencies
      - approve:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - approve
